### ISSUE TITLE
How to use + as suffix?

### ISSUE THREAD

**Issue by kaangokdemir** [fredericojordan/progress-bar#3]
Cool project. Just wonder how to use `+` as suffix since using like https://progress-bar.dev/20/?scale=10&title=rewards&suffix=+ is not working as I expected.

**Comment by fredericojordan** [comment]
Thanks!
Seems like using `+`  is not supported at the moment, I'll have to take a look at why this is the case.
I'll let you know as soon as it's fixed!

**Comment by fredericojordan** [comment]
Actually, you can just escape it with [url encoding](https://en.wikipedia.org/wiki/Percent-encoding) (`%2B`) like this:
https://progress-bar.dev/20/?scale=10&title=rewards&suffix=%2B
![progress](https://progress-bar.dev/20/?scale=10&title=rewards&suffix=%2B)

**Comment by fredericojordan** [comment]
@kaangokdemir Thanks for reaching out, I'm closing this one for now. 🙂
